In [75]:
import numpy as np

with open("..\data\stage2\calibset1.txt") as fl:
    calib_data=fl.read().split('\n\n')

with open("..\data\stage2\dataset2.txt") as fl:
    test_data=fl.read().split('\n\n')

In [76]:
R,G,B,K,W=calib_data
sel_calib_data=R,G,B,W
ex=np.array([tuple(map(int,line.split('\n')[0].split(','))) for line in sel_calib_data])
rd=np.array([tuple(map(int,line.split('\n')[1].split(',')))+(1,) for line in sel_calib_data])


print(ex)
# print()
print(rd)
ex_v=np.split(ex,3,1)

# print(ex_v[0])

coffs=[np.matmul(np.linalg.inv(rd),ex_v[i]) for i in range(3)]
# print(coffs)

for r in rd:    
    print([round(np.matmul(r,coffs[i])[0]) for i in range(3)])



[[255   0   0]
 [  0 255   0]
 [  0   0 255]
 [255 255 255]]
[[660 131 125   1]
 [397 236 126   1]
 [303 161 214   1]
 [663 337 306   1]]
[255, 0, 0]
[0, 255, 0]
[0, 0, 255]
[255, 255, 255]


In [77]:
test_ex=np.array([tuple(map(int,line.split('\n')[0].split(','))) for line in test_data])
test_rd=np.array([tuple(map(int,line.split('\n')[1].split(',')))+(1,) for line in test_data])


def mat_delta(m1,m2):
    delta=[]
    for i in range(3):        
        if m2[i]<0:m2[i]=0
        elif m2[i]>255:m2[i]=255
        delta.append(m1[i]-m2[i])

    print(m1,m2,delta)
    return delta

for k in range(len(test_rd)):
    calc=[round(np.matmul(test_rd[k],coffs[i])[0]) for i in range(3)]
    mat_delta(test_ex[k],calc)
    


[204   0   0] [191, 0, 1] [13, 0, -1]
[153   0   0] [130, 0, 3] [23, 0, -3]
[102   0   0] [57, 0, 18] [45, 0, -18]
[51  0  0] [11, 0, 27] [40, 0, -27]
[255 127   0] [224, 127, 0] [31, 0, 0]
[204 102   0] [179, 74, 0] [25, 28, 0]
[153  77   0] [125, 42, 0] [28, 35, 0]
[102  52   0] [66, 13, 12] [36, 39, -12]
[51 27  0] [9, 6, 19] [42, 21, -19]
[255 255   0] [169, 255, 0] [86, 0, 0]
[204 204   0] [152, 255, 0] [52, -51, 0]
[153 153   0] [101, 232, 0] [52, -79, 0]
[102 102   0] [40, 101, 0] [62, 1, 0]
[51 51  0] [0, 33, 14] [51, 18, -14]
[  0 204   0] [0, 236, 2] [0, -32, -2]
[  0 153   0] [0, 216, 3] [0, -63, -3]
[  0 102   0] [0, 147, 20] [0, -45, -20]
[ 0 51  0] [0, 43, 37] [0, 8, -37]
[  0   0 204] [0, 0, 211] [0, 0, -7]
[  0   0 153] [0, 0, 149] [0, 0, 4]
[  0   0 102] [0, 0, 93] [0, 0, 9]
[ 0  0 51] [0, 0, 54] [0, 0, -3]
[ 75   0 130] [16, 0, 202] [59, 0, -72]
[ 60   0 104] [10, 0, 170] [50, 0, -66]
[45  0 78] [0, 0, 104] [45, 0, -26]
[30  0 52] [0, 0, 73] [30, 0, -21]
[15  0 26] [0

In [3]:
#Max/Min method
import numpy as np

with open("..\data\stage2\calibset1.txt") as fl:
    calib_data=fl.read().split('\n\n')

with open("..\data\stage2\dataset2.txt") as fl:
    test_data=fl.read().split('\n\n')

In [5]:

ex=np.array([tuple(map(int,line.split('\n')[0].split(','))) for line in calib_data])
rd=np.array([tuple(map(int,line.split('\n')[1].split(','))) for line in calib_data])

print(ex)
print(rd)
coffs=[]

ex_h=ex[4][0]
ex_l=ex[3][0]

for i in range(3):
    rd_h=rd[i][i]
    rd_l=max(rd[(i+1)%3][i],rd[(i+2)%3][i])

    m=(ex_h-ex_l)/(rd_h-rd_l)
    c=-rd_l*m+ex_l

    coffs.append((m,c))


print(coffs)
# def trim(x):
#     if x<ex_l:x=ex_l
#     elif x>ex_h:x=ex_h
#     return round(x)

def trim(x):
    if x<0:x=0
    elif x>255:x=255
    return round(x)

def cal(rd_i):
    l=[]
    for i in range(3):
        cal_v=rd_i[i]*coffs[i][0]+coffs[i][1]        
        l.append(trim(cal_v))
    return l

def delta(m1,m2):
    _delta=[]
    for i in range(3):   
        _delta.append(m1[i]-m2[i])    
    return _delta


[[255   0   0]
 [  0 255   0]
 [  0   0 255]
 [  0   0   0]
 [255 255 255]]
[[660 131 125]
 [397 236 126]
 [303 161 214]
 [306 104  98]
 [663 337 306]]
[(0.9695817490494296, -384.92395437262354), (3.4, -547.4), (2.897727272727273, -365.1136363636364)]


In [6]:

for i in range(len(rd)):
    cal_v=cal(rd[i])
    print(ex[i],cal_v,delta(ex[i],cal_v))

[255   0   0] [255, 0, 0] [0, 0, 0]
[  0 255   0] [0, 255, 0] [0, 0, 0]
[  0   0 255] [0, 0, 255] [0, 0, 0]
[0 0 0] [0, 0, 0] [0, 0, 0]
[255 255 255] [255, 255, 255] [0, 0, 0]


In [8]:
ex_o=np.array([tuple(map(int,line.split('\n')[0].split(','))) for line in test_data])
rd_i=np.array([tuple(map(int,line.split('\n')[1].split(','))) for line in test_data])

print(rd_i)


for i in range(len(rd_i)):
    cal_v=cal(rd_i[i])
    print(ex_o[i],cal_v,delta(ex_o[i],cal_v))


[[579 113 111]
 [506 111 103]
 [414 104  98]
 [354  93  92]
 [658 180 108]
 [590 149 100]
 [513 130  97]
 [430 115 100]
 [357 105  92]
 [661 326 121]
 [623 293 118]
 [528 220 104]
 [420 152  95]
 [333 115  90]
 [367 223 120]
 [360 212 116]
 [341 178 112]
 [310 124 101]
 [297 138 186]
 [295 127 153]
 [294 112 122]
 [293 103 101]
 [325 129 182]
 [323 120 164]
 [304 110 128]
 [302 106 112]
 [308 104 104]
 [401 136 189]
 [390 133 189]
 [351 119 176]
 [321 117 145]
 [305 104 104]
 [611 286 262]
 [528 216 194]
 [414 144 129]
 [334 109 100]]
[204   0   0] [176, 0, 0] [28, 0, 0]
[153   0   0] [106, 0, 0] [47, 0, 0]
[102   0   0] [16, 0, 0] [86, 0, 0]
[51  0  0] [0, 0, 0] [51, 0, 0]
[255 127   0] [253, 65, 0] [2, 62, 0]
[204 102   0] [187, 0, 0] [17, 102, 0]
[153  77   0] [112, 0, 0] [41, 77, 0]
[102  52   0] [32, 0, 0] [70, 52, 0]
[51 27  0] [0, 0, 0] [51, 27, 0]
[255 255   0] [255, 255, 0] [0, 0, 0]
[204 204   0] [219, 255, 0] [-15, -51, 0]
[153 153   0] [127, 201, 0] [26, -48, 0]
[102 102   