In [3]:
import numpy as np

with open("..\data\stage2\calibset2.txt") as fl:
    calib_data=fl.read().split('\n\n')

In [4]:
R,G,B,K,W=calib_data
sel_calib_data=R,G,B,W
ex=np.array([tuple(map(int,line.split('\n')[0].split(','))) for line in sel_calib_data])
rd=np.array([tuple(map(int,line.split('\n')[1].split(','))) for line in sel_calib_data])


print(ex)
print()
print(rd)

for row in rd:
    row.


[[204   0   0]
 [  0 204   0]
 [  0   0 204]
 [204 204 204]]

[[579 113 111]
 [367 223 120]
 [297 138 186]
 [611 286 262]]
